//GET COMPANYS PROFILE: ONLY ADMINS CAN GET ALL COMPANYS
export const GET_COMPANY_PROFILE_REQUEST = "GET_COMPANY_PROFILE_REQUEST";
export const GET_COMPANY_PROFILE_SUCCESS = "GET_COMPANY_PROFILE_SUCCESS";
export const GET_COMPANY_PROFILE_FAILURE = "GET_COMPANY_PROFILE_FAILURE";
export const GET_COMPANY_PROFILE_RESET = "GET_COMPANY_PROFILE_RESET";

//ADMIN UPDATE PROFILE
export const ADMIN_UPDATE_COMPANY_PROFILE_REQUEST = "ADMIN_UPDATE_COMPANY_PROFILE_REQUEST";
export const ADMIN_UPDATE_COMPANY_PROFILE_SUCCESS = "ADMIN_UPDATE_COMPANY_PROFILE_SUCCESS";
export const ADMIN_UPDATE_COMPANY_PROFILE_FAILURE = "ADMIN_UPDATE_COMPANY_PROFILE_FAILURE";
export const ADMIN_UPDATE_COMPANY_PROFILE_RESET = "ADMIN_UPDATE_COMPANY_PROFILE_RESET";

//GET COMPANYS BASIC DETAILS
export const GET_COMPANY_DETAILS_REQUEST = "GET_COMPANY_DETAILS_REQUEST";
export const GET_COMPANY_DETAILS_SUCCESS = "GET_COMPANY_DETAILS_SUCCESS";
export const GET_COMPANY_DETAILS_FAILURE = "GET_COMPANY_DETAILS_FAILURE";



